### ISSUE TITLE
电脑上图片是裂的，手机上能看，不知道是不是个人原因。

### ISSUE THREAD

**Issue by RainbowDashKira** [Perseus037/nonebot_plugin_batarot#1]
群友反馈电脑上看到也是裂的，手机上能看到图。对于我个人，手机电脑机器人是一个网络环境。四个指令返回的图电脑看都是裂的。
![image](https://github.com/Perseus037/nonebot_plugin_batarot/assets/117131527/a873098a-ed72-443a-b267-033606f93151)

**Comment by Perseus037** [comment]
我待会再推一个仓库，把图片格式改成jpg试试，可能是png图片对于旧版本的qq兼容性有问题
我自己用的qqnt，没有出现过类似的情况
<img width="517" alt="image" src="https://github.com/Perseus037/nonebot_plugin_batarot/assets/143330850/e56cd1c0-d8c2-4e53-85f8-cd40794d5eb9">

**Comment by Perseus037** [comment]
下载新发布的release，或者直接把旧的batarot_url文件替换成新的应该就能解决问题了（我建议直接下新的，改了很多东西）
|自己找群友测试了一下，现在pc端老版qq应该也能正常看到图片了。
