### ISSUE TITLE
能否添加占卜的转发以及一条消息包含切换的设置选项

### ISSUE THREAD

**Issue by DreamGallery** [Perseus037/nonebot_plugin_batarot#10]
我记得之前好像是一张塔罗牌一张塔罗牌转发消息，现在是合在一起了，不过合在一起就有点太长了，会刷屏，最好能添加一个切换的flag

**Comment by Perseus037** [comment]
Message Factory不支持合并转发，所以当时选择改成逐条发送
nb的nodes.append对新版qqnt不适配，或者说同一个命令新老版本qq有冲突，我也有很长一段时间没有去学习新的nb文档了，实在是太忙。没有空闲时间。
你可以打开这个插件的v0.2.1的commands.py，找到handle_tarot_spread异步函数，这是我之前写的合并转发函数，并结合nb文档中关于nodes.append的部分来自行修改。

**Comment by DreamGallery** [comment]
好的，辛苦大佬了，我到时候自己去看看

**Comment by DreamGallery** [comment]
哦，好像是私聊直接一整条消息，群聊是消息转发，那没问题了，似乎是我记错了WWW
