### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by MWTJC** [Perseus037/nonebot_plugin_batarot#2]
运行插件报错`ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED]`，
可采用的解决方法：`utils.py`中，`async with session.get(url) as response:`加参数改为`async with session.get(url, ssl=False) as response:`

**Comment by Perseus037** [comment]
这个不是代码本身的问题喵，但是可以试试下面的几种方法看看能不能解决
可以先试试更新一下python的certifi包，刚看了一眼，目前的最新版本是2023.11.17
有时候证书库版本太老的话可能会出现ssl证书验证报错
不过我猜大概率是因为你挂梯子了，system proxy也可能会导致出现ssl报错，改为tun模式使用虚拟网卡应该就不会报错了
如果还是解决不了，加个ssl=False来直接禁用也不会影响插件的正常运行，但是我个人不建议禁用ssl验证，安全风险比较高

**Comment by Perseus037** [comment]
如果没有其他问题了的话我就关掉issue了（）

**Comment by MWTJC** [comment]
> 这个不是代码本身的问题喵，但是可以试试下面的几种方法看看能不能解决 可以先试试更新一下python的certifi包，刚看了一眼，目前的最新版本是2023.11.17 有时候证书库版本太老的话可能会出现ssl证书验证报错 不过我猜大概率是因为你挂梯子了，system proxy也可能会导致出现ssl报错，改为tun模式使用虚拟网卡应该就不会报错了 如果还是解决不了，加个ssl=False来直接禁用也不会影响插件的正常运行，但是我个人不建议禁用ssl验证，安全风险比较高

我还没得条件和需求在bot上挂梯子属于是…我bot环境确实比较老，去年5月搭的，但拿pip升级了certifi，似乎不管用；我就改代码先用着了，毕竟我这应该也不存在啥安全问题（破nas上肯定没得高价值目标所以不验证ssl应该也没逝）

**Comment by Xiao-yux** [comment]
![image](https://github.com/Perseus037/nonebot_plugin_batarot/assets/79674967/de9660a9-3e12-4a93-9933-28db153df468)
能添加一个代理选项吗

**Comment by Xiao-yux** [comment]
> > 这个不是代码本身的问题喵，但是可以试试下面的几种方法看看能不能解决 可以先试试更新一下python的certifi包，刚看了一眼，目前的最新版本是2023.11.17 有时候证书库版本太老的话可能会出现ssl证书验证报错 我猜不过大概率是因为你挂梯子了，system proxy也可能会导致出现ssl报错，改为tun模式使用虚拟网卡应该就不会报错了 如果还是解决不了，加个ssl=False来直接禁用也不会影响插件的正常运行，但是我个人不建议禁用ssl验证，安全风险比较高
> 
> 我还没得条件和需求在bot上挂梯子属于是...我bot环境确实比较老，去年5月搭的，但拿pip升级了certifi，似乎不管用;我就改代码先用着了，毕竟我这应该也不存在啥安全问题（破nas上肯定没得高价值目标所以不验证ssl应该也没逝）

能添加一个代理选项吗

**Comment by Perseus037** [comment]
我建议你改源码直接忽略证书验证就好，如果开vpn了的话关掉或者切换其他节点试试也可能就不跳这个报错了。
