### ISSUE TITLE
好好的插件爱你

### ISSUE THREAD

**Issue by 360add** [Perseus037/nonebot_plugin_batarot#6]

**Comment by 360add** [comment]
但是有个问题，单发ba塔罗牌没有正位或者逆位，只有牌解读

**Comment by Perseus037** [comment]
<img width="547" alt="71327ff28d91a04fd2d9bba9076a658a" src="https://github.com/Perseus037/nonebot_plugin_batarot/assets/143330850/cc242f72-14ce-4767-be60-18ef04b529c3">
实测没有问题，发一下错误日志

**Comment by 360add** [comment]
是这样的，我意思是还以为这个塔罗牌指令也能有个随机正位逆位

**Comment by Perseus037** [comment]
你改一下command.py里handle_taroth函数下的reply_text，给card_meaning加一个random方法就行 
![image](https://github.com/Perseus037/nonebot_plugin_batarot/assets/143330850/3b8fe367-3f51-4700-a396-0151cbb1caf1)

**Comment by 360add** [comment]
好的，感谢🙇‍
