### ISSUE TITLE
塔罗牌解读使用不了

### ISSUE THREAD

**Issue by YRRLYB** [Perseus037/nonebot_plugin_batarot#7]
我输入指令/ba塔罗牌解读 20或者是/ba塔罗牌解读 女皇。都是使用不了的，他只会跟我说：未找到指定的塔罗牌或输入格式错误，请输入正确的卡牌编号或名称。

**Comment by Perseus037** [comment]
我看一下，今天晚上或者明天推一个新的版本出来，顺便换一下图床
