### ISSUE TITLE
塔罗牌图片资源可以保存在本地吗，联网下载太慢了

### ISSUE THREAD

**Issue by 360add** [Perseus037/nonebot_plugin_batarot#8]
塔罗牌图片资源可以保存在本地吗，联网下载太慢了，等一分钟才收到回复

**Comment by Perseus037** [comment]
如果你需要的话，我可以私发你全部的图片，你自己改一下路径本地读取就行。
传送速度慢的话可以试试挂vpn，我是用的免费的图床，速度慢也确实没办法w

**Comment by 360add** [comment]
害，不知道咋改

**Comment by 360add** [comment]
真的要改成本地，如果用占卜指令牌多，等两分钟才收到回复

**Comment by Perseus037** [comment]
理论上来说从本地直接发应该是响应速度应该是很快的，等我有空改个从本地发的版本

**Comment by DreamGallery** [comment]
我是自己去把所有图片下载下来然后上传了另外的图床，换了链接，原来的确有点慢了

**Comment by Perseus037** [comment]
> 真的要改成本地，如果用占卜指令牌多，等两分钟才收到回复

我推了一个新的版，你直接git pull一下就行，现在应该速度比以前快多了。
你也可以直接在你的bot目录下的site-packages文件夹，找到nonebot_plugin_batraot，用github上的batarot_url.json替换原来的文件也可以。

**Comment by Perseus037** [comment]
> 我是自己去把所有图片下载下来然后上传了另外的图床，换了链接，原来的确有点慢了
换了个国内外都能用的图床w，确实速度快很多

**Comment by Perseus037** [comment]
> 我是自己去把所有图片下载下来然后上传了另外的图床，换了链接，原来的确有点慢了

换了个国内外都能用的图床，确实快很多

**Comment by DreamGallery** [comment]
> 换了个国内外都能用的图床，确实快很多

我现在用的就是sm.ms,还行

**Comment by 360add** [comment]
一劳永逸就是放在本地

**Comment by 360add** [comment]
> > 换了个国内外都能用的图床，确实快很多
> 
> 我现在用的就是sm.ms,还行

你这弄的，现在作者换图片地址了，不做本地了

**Comment by 360add** [comment]
> > 换了个国内外都能用的图床，确实快很多
> 
> 我现在用的就是sm.ms,还行



> > 换了个国内外都能用的图床，确实快很多
> 
> 我现在用的就是 sm.ms，还行

现在图链又挂了
